---
# renovate: datasource=github-releases depName=asdf-vm/asdf
asdf_version: v0.13.1

# renovate: datasource=github-releases depName=sharkdp/hyperfine
hyperfine_version: v1.18.0

# renovate: datasource=github-releases depName=mr-karan/doggo
doggo_version: v0.5.7
